services:
  controle-financeiro:
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8520:8520"
    volumes:
      - ./.env:/app/.env
      - ./csv/:/app/csv/
      - ~/.streamlit:/root/.streamlit
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8520
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
